### ISSUE TITLE
Json Error

### ISSUE THREAD

**Issue by arthur4ires** [swisskyrepo/GraphQLmap#30]
Error on dump_new command:

arthur@basidqh23ofia GraphQLmap]$ python graphqlmap.py -u http://35.190.155.168/24e52a10fc/graphql -v 
   _____                 _      ____  _                            
  / ____|               | |    / __ \| |                           
 | |  __ _ __ __ _ _ __ | |__ | |  | | |     _ __ ___   __ _ _ __  
 | | |_ | '__/ _` | '_ \| '_ \| |  | | |    | '_ ` _ \ / _` | '_ \ 
 | |__| | | | (_| | |_) | | | | |__| | |____| | | | | | (_| | |_) |
  \_____|_|  \__,_| .__/|_| |_|\___\_\______|_| |_| |_|\__,_| .__/ 
                  | |                                       | |    
                  |_|                                       |_|    
                              Author: @pentest_swissky Version: 1.0 

GraphQLmap > dump_new
Traceback (most recent call last):
  File "/home/arthur/Ferramentas/GraphQLmap/graphqlmap.py", line 78, in <module>
    GraphQLmap(args)
  File "/home/arthur/Ferramentas/GraphQLmap/graphqlmap.py", line 53, in __init__
    dump_schema(self.url, self.method, 15, self.headers, self.use_json)
  File "/home/arthur/Ferramentas/GraphQLmap/attacks.py", line 31, in dump_schema
    schema = r.json()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AdnanHussainTurki** [comment]
How you resolved this?
