### ISSUE TITLE
KeyError: 'data"

### ISSUE THREAD

**Issue by BartekSmalec** [swisskyrepo/GraphQLmap#39]
Hey, what may be a reason of this kind of error ? 
`bartek@ubuntu:~/Programs/GraphQLmap$ graphqlmap -u https://****.com/gateway?query={} 
   _____                 _      ____  _                            
  / ____|               | |    / __ \| |                           
 | |  __ _ __ __ _ _ __ | |__ | |  | | |     _ __ ___   __ _ _ __  
 | | |_ | '__/ _` | '_ \| '_ \| |  | | |    | '_ ` _ \ / _` | '_ \ 
 | |__| | | | (_| | |_) | | | | |__| | |____| | | | | | (_| | |_) |
  \_____|_|  \__,_| .__/|_| |_|\___\_\______|_| |_| |_|\__,_| .__/ 
                  | |                                       | |    
                  |_|                                       |_|    
                              Author: @pentest_swissky Version: 1.0 
GraphQLmap > dump_via_introspection
============= [SCHEMA] ===============
e.g: name[Type]: arg (Type!)

Traceback (most recent call last):
  File "/usr/local/bin/graphqlmap", line 4, in <module>
    __import__('pkg_resources').run_script('graphqlmap==0.0.1', 'graphqlmap')
  File "/home/bartek/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 656, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/bartek/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/graphqlmap-0.0.1-py3.8.egg/EGG-INFO/scripts/graphqlmap", line 81, in <module>
  File "/usr/local/lib/python3.8/dist-packages/graphqlmap-0.0.1-py3.8.egg/EGG-INFO/scripts/graphqlmap", line 56, in __init__
  File "/usr/local/lib/python3.8/dist-packages/graphqlmap-0.0.1-py3.8.egg/graphqlmap/attacks.py", line 39, in dump_schema
KeyError: 'data'
`
I've got this error using **dump_via_fragment** and **dump_via_introspection** on two different endpoint. Configuration of the endpoints my be the reason ?

**Comment by mo-at-dave** [comment]
I'm also seeing this
