### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by qodirovhamidjon** [swisskyrepo/GraphQLmap#5]
#python3 graphqlmap.py -u http://example.com/p/graphql --method
   _____                 _      ____  _                            
  / ____|               | |    / __ \| |                           
 | |  __ _ __ __ _ _ __ | |__ | |  | | |     _ __ ___   __ _ _ __  
 | | |_ | '__/ _` | '_ \| '_ \| |  | | |    | '_ ` _ \ / _` | '_ \ 
 | |__| | | | (_| | |_) | | | | |__| | |____| | | | | | (_| | |_) |
  \_____|_|  \__,_| .__/|_| |_|\___\_\______|_| |_| |_|\__,_| .__/ 
                  | |                                       | |    
                  |_|                                       |_|    
                              Author: @pentest_swissky Version: 1.0 
GraphQLmap > dump_new
Traceback (most recent call last):
  File "graphqlmap.py", line 71, in <module>
    GraphQLmap(args)
  File "graphqlmap.py", line 47, in __init__
    dump_schema(self.url, self.method, 15)
  File "/root/GraphQLmap/attacks.py", line 36, in dump_schema
    schema = r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by alimp5** [comment]
Hi dear
I got below error in windows 10 on python 3.7.x 64 bit:

>  
> Traceback (most recent call last):
>   File ".\graphqlmap.py", line 75, in <module>
>     GraphQLmap(args)
>   File ".\graphqlmap.py", line 35, in __init__
>     self.headers = None if not args_graphql.headers else json.loads(args_graphql.headers)
>   File "C:\Python37\lib\json\__init__.py", line 348, in loads
>     return _default_decoder.decode(s)
>   File "C:\Python37\lib\json\decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "C:\Python37\lib\json\decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by duraki** [comment]
@swisskyrepo same here
