### ISSUE TITLE
Issue launching GraphQLmap.py - import module not found

### ISSUE THREAD

**Issue by 24allday** [swisskyrepo/GraphQLmap#51]
Previously it was working fine however, I had to reinstall WSL and try to install GraphQLmap again. When I attempted to, it threw an error once I had extracted the repo and attempted to run the binary from the bin folder provided. I am not sure but, the first time round, installing this was no issue at all.

For example:

Called from: ~/GraphQLmap/bin
Command: ./graphqlmap

Error:
Traceback (most recent call last):
  File "/home/{$user}/GraphQLmap/bin/./graphqlmap", line 8, in <module>
    from graphqlmap.attacks import *
ModuleNotFoundError: No module named 'graphqlmap'

Apparently there is an outdated version of something, I have included the error message when attempting to launch setup.py with python3.

 warnings.warn(
Traceback (most recent call last):
  File "/home/ori/GraphQLmap/setup.py", line 6, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 335, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2679, in parsed_version
    self._parsed_version = parse_version(self.version)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/version.py", line 266, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '1.4-py1'
(package: adns)

I would like to use the tool so any advice on getting it to work is useful. I have tried uninstalling, moving the file to another DIR and also moving to bin. As mentioned, it has worked fine before but, I had an issue which forced me to restart my WSL so I am not sure if that issue is connected.

**Comment by Bizarrus** [comment]
Same here:

```
❯ python3 setup.py install
Traceback (most recent call last):
  File "/var/www/knuddels/GraphQL/setup.py", line 1, in <module>
    import setuptools
ModuleNotFoundError: No module named 'setuptools'
````
